# BACKGROUND
background {
    monitor =
    path = /usr/share/sddm/themes/silent/backgrounds/rei.png # Takes a screenshot of your current screen and blurs it
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2 # High quality blur
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vignette = true
    vignette_thickness = 0.3
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 120
    font_family = CaskaydiaCove Nerd Font Bold
    position = 0, -100
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(255, 255, 255, 0.6)
    font_size = 24
    font_family = CaskaydiaCove Nerd Font
    position = 0, -300
    halign = center
    valign = top
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgba(255, 255, 255, 0.8)
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before fade_on_empty kicks in
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box
    hide_input = false
    rounding = -1 # -1 means complete rounding
    check_color = rgba(204, 136, 34, 1.0)
    fail_color = rgba(204, 34, 34, 1.0) # if authentication failed
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be substituted with something custom
    fail_transition = 300 # transition time in ms between normal item and fail
    position = 0, -100
    halign = center
    valign = center

    # AUTOMATIC UNLOCK FEATURE
    key_id_trigger = true # Validates password instantly on keypress without Enter
}

# USER GREETING
label {
    monitor =
    text = Welcome back, $USER
    color = rgba(255, 255, 255, 0.6)
    font_size = 18
    font_family = CaskaydiaCove Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

